### ISSUE TITLE
Model in MVVM

### ISSUE THREAD

**Issue by serejahh** [artemkalinovsky/PinPlace#1]
Hi Artem! Thanks for your project
I have a question. Where are `models` according MVVM? For instance, PlacesMapViewController has an instance of CLLocationManage. In other words a view contains logic

**Comment by artemkalinovsky** [comment]
Hey,
Thanks for your comment!
Please, check this commit https://github.com/artemkalinovsky/PinPlace/commit/f9ce28d90d3d1fbb790771830cf13c7bad462b18
